public with sharing class QueryApiProvider implements IQueryApi {
//    private QueryApiService queryApiService;
//    
//    public QueryApiProvider(ICallout calloutClient) {
//        this.queryApiService = new QueryApiService(calloutClient);
//    }

//    public List<SObject> getRecordsByObjectName(String objectName, Integer limitCount) {
//         
//         return this.queryApiService.getRecordsByObjectName(objectName, limitCount);
//    }

//    public List<SObject> getRecordsByObjectNameAndQuery(String objectName, String customQuery) {
//        return null;
//    }

    public List<SObject> getRecordsByObjectName(String objectName, Integer limitCount) {
        return null;
    }

    public List<SObject> getRecordsByObjectNameAndQuery(String objectName, String customQuery) {
        return null;
    }
}